# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  kol_levels:
    :A: 100
    :B: 50
    :C: 10
    :S: 5000
  domain: 'http://test.robin8.net'
  secret_key_base: 9b38aee9da7ab2bfb9e10637cf4d0fa9b642dc1a84f85ad42f4cfb182cfd231931beb8b50b79e5f7677555a41d9358aaf8f1a709ff1f350059ffde1dfe6b9074
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234
  host: localhost
  instance_host:
    cn: ''
    en: ''
  textapi:
    :app_id: c0472211
    :app_key: f0f61d22c235b7e1bef2c7ff7f8dfa09
  mailgun:
    :api_base_url: https://api.mailgun.net/v2/mg.robin8.com
    :api_key: key-11db1b65d448b9104326804bf5804a25
    :send_domain: mg.robin8.com
    :from: 'Robin8 <noreply@mg.robin8.com>'
  # sendcloud for chinainstance
  sendcloud:
    :api_key: HwhgxnYhvKwPIvlV
    :api_user: robin8_test_UZ6mI5 # test user, updated later
    :from_name: Robin8
    :from_address: noreply@robin8.net
  smtp:
    :user_name: postmaster@mg.robin8.com
    :password: 779fdf44652d019612a11ad54dd181c0
    :domain: mg.robin8.com
    :address: smtp.mailgun.org
    :port: 587
  google:
    :client_id: '411343306765-qaokd4h3f7tivl2oo423shd54k30a6eo.apps.googleusercontent.com'
    :client_secret: '356dA9S4y5IbB-WpIhcX06rh'
  facebook:
    :app_id: '1581983398705792'
    :app_secret: '35049632231f31ffe301af15b21ad218'
  twitter:
    :api_key: 'chfbNFBkf56gJT2BDzmCNNfgv'
    :api_secret: 'WJvtq91oZgvGIJQl33J8kprn4eeWRlCzj4qlYulAyzwuxKATS3'
  linkedin:
    :api_key: '75qazimsj55zfi'
    :api_secret: 'UqTqTg4UCTBxo33u'
  uploadcare: 'eaef90e4420402169d1f:09b94a326a95086338d6'
  amazon:
    :key_id: 'AKIAJBAZFWNSWK6XHBQQ'
    :secret_access_key: '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'
  devise:
    secret_key: '08d9741592f4729aae97cbd8f3ff37300b164d99cefdebca6b9c4561dc46fda14b8bca0a5e160cbe13404e1bfac8d75476ac64f10d1fafceb9a98117ee101736'
  bluesnap:
    :user: "API_14177682984271105511385"
    :password: "Robin123"
    :store_id: "14253"
    :public_key: "10001$e1c3042d3facf7bd48f4fe4149c0711ff96c350c4ff41c7a0515c06e32322531c6d609d45f292bc006907086963d4cdef11849a4dd8eb6d629cbd2fed35f7ac44b25ae61a5c9b449bad56802e7bed9a7530c71855cd3c698a90b03a3c46de1074b0af2773e0223ea87c86b5a86e7eab6cf50bdc6063864a422e1d03acd6d1e03dcaab283c126fa576871e4c233c6383658a9cc048d4aabaa2519fc4088a7b62e9ee670b2fe340969d1fefb5b1aab7d8f3339f1c4e974baeffcf00c2f7d6da5327341e00fa89cd27890d01f9cabf7f082a7cda87b86694b684485100309a14f96ebefcd28b64761c26c51f83c5f1bbe31564dac6863f5888877d97e5cbde56de7"
    :base_url: "https://sandbox.bluesnap.com/services/2"
  yunpian:
    :api_key: "250b960f00ba9c461fc7559cb7740da2"
    :company_sign: "罗宾科技"
  qiniu:
    :access_key: "5bRVzHodaZbSwt6lLpO75opJo-TuSJyRoTlwkAON"
    :secret_key:  "RGzmCELncrd_AySF6hht0gElCtC0zxB2tWOjkIi7"

test:
  secret_key_base: 110dfb851be877fea669a4bd53e865de4444769e3aa5d5c5750eba6e1f81c11bf36bdbe209859de602c7a8a5f7226b160365aaff600795ffdd7087500fc91e62
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234
  devise:
    secret_key: '08d9741592f4729aae97cbd8f3ff37300b164d99cefdebca6b9c4561dc46fda14b8bca0a5e160cbe13404e1bfac8d75476ac64f10d1fafceb9a98117ee101736'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9b38aee9da7ab2bfb9e10637cf4d0fa9b642dc1a84f85ad42f4cfb182cfd231931beb8b50b79e5f7677555a41d9358aaf8f1a709ff1f350059ffde1dfe6b9074
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234
  host: localhost
  textapi:
    :app_id: c0472211
    :app_key: f0f61d22c235b7e1bef2c7ff7f8dfa09
  mailgun:
    :api_base_url: https://api.mailgun.net/v2/mg.robin8.com
    :api_key: key-11db1b65d448b9104326804bf5804a25
  smtp:
    :user_name: postmaster@mg.robin8.com
    :password: 779fdf44652d019612a11ad54dd181c0
    :domain: mg.robin8.com
    :address: smtp.mailgun.org
    :port: 587
  redis:
    :url: redis://127.0.0.1:6379/0
  google:
    :client_id: '411343306765-qaokd4h3f7tivl2oo423shd54k30a6eo.apps.googleusercontent.com'
    :client_secret: '356dA9S4y5IbB-WpIhcX06rh'
  facebook:
    :app_id: '1581983398705792'
    :app_secret: '35049632231f31ffe301af15b21ad218'
  twitter:
    :api_key: 'chfbNFBkf56gJT2BDzmCNNfgv'
    :api_secret: 'WJvtq91oZgvGIJQl33J8kprn4eeWRlCzj4qlYulAyzwuxKATS3'
  linkedin:
    :api_key: '75qazimsj55zfi'
    :api_secret: 'UqTqTg4UCTBxo33u'
  uploadcare: 'eaef90e4420402169d1f:09b94a326a95086338d6'
  amazon:
    :key_id: 'AKIAJBAZFWNSWK6XHBQQ'
    :secret_access_key: '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'
  devise:
    secret_key: '08d9741592f4729aae97cbd8f3ff37300b164d99cefdebca6b9c4561dc46fda14b8bca0a5e160cbe13404e1bfac8d75476ac64f10d1fafceb9a98117ee101736'
  bluesnap:
    :user: "API_14177682984271105511385"
    :password: "Robin123"
    :store_id: "14253"
    :public_key: "10001$e1c3042d3facf7bd48f4fe4149c0711ff96c350c4ff41c7a0515c06e32322531c6d609d45f292bc006907086963d4cdef11849a4dd8eb6d629cbd2fed35f7ac44b25ae61a5c9b449bad56802e7bed9a7530c71855cd3c698a90b03a3c46de1074b0af2773e0223ea87c86b5a86e7eab6cf50bdc6063864a422e1d03acd6d1e03dcaab283c126fa576871e4c233c6383658a9cc048d4aabaa2519fc4088a7b62e9ee670b2fe340969d1fefb5b1aab7d8f3339f1c4e974baeffcf00c2f7d6da5327341e00fa89cd27890d01f9cabf7f082a7cda87b86694b684485100309a14f96ebefcd28b64761c26c51f83c5f1bbe31564dac6863f5888877d97e5cbde56de7"
    :base_url: "https://sandbox.bluesnap.com/services/2"
  yunpian:
    :api_key: "250b960f00ba9c461fc7559cb7740da2"
    :company_sign: "罗宾科技"
  wechat:
    :app_id:  wxc04b5dd96c14ae29
    :app_secret: d4624c36b6795d1d99dcf0547af5443d
    :aes_key: eada1a9c14848c8840f720db0167885beada1a9c148
 data_engine_url:
    :weibo: 'http://engine-api.robin8.net/api/v1/kols/weibo/'
    :wechat: 'http://engine-api.robin8.net/api/v1/kols/wx_public/'
    :discover: 'http://engine-api.robin8.net/api/v1/articles/'

staging:
  secret_key_base: 9b38aee9da7ab2bfb9e10637cf4d0fa9b642dc1a84f85ad42f4cfb182cfd231931beb8b50b79e5f7677555a41d9358aaf8f1a709ff1f350059ffde1dfe6b9074
  robin_api_url: http://robin8.cloudhub.io/api/v1
  robin_api_user: perfectial@aylien.com
  robin_api_pass: abcd1234
  host: localhost
  textapi:
    :app_id: c0472211
    :app_key: f0f61d22c235b7e1bef2c7ff7f8dfa09
  mailgun:
    :api_base_url: https://api.mailgun.net/v2/mg.robin8.com
    :api_key: key-11db1b65d448b9104326804bf5804a25
  smtp:
    :user_name: postmaster@mg.robin8.com
    :password: 779fdf44652d019612a11ad54dd181c0
    :domain: mg.robin8.com
    :address: smtp.mailgun.org
    :port: 587
  google:
    :client_id: '411343306765-qaokd4h3f7tivl2oo423shd54k30a6eo.apps.googleusercontent.com'
    :client_secret: '356dA9S4y5IbB-WpIhcX06rh'
  facebook:
    :app_id: '1581983398705792'
    :app_secret: '35049632231f31ffe301af15b21ad218'
  twitter:
    :api_key: 'chfbNFBkf56gJT2BDzmCNNfgv'
    :api_secret: 'WJvtq91oZgvGIJQl33J8kprn4eeWRlCzj4qlYulAyzwuxKATS3'
  linkedin:
    :api_key: '75qazimsj55zfi'
    :api_secret: 'UqTqTg4UCTBxo33u'
  uploadcare: 'eaef90e4420402169d1f:09b94a326a95086338d6'
  amazon:
    :key_id: 'AKIAJBAZFWNSWK6XHBQQ'
    :secret_access_key: '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'
  devise:
    secret_key: '08d9741592f4729aae97cbd8f3ff37300b164d99cefdebca6b9c4561dc46fda14b8bca0a5e160cbe13404e1bfac8d75476ac64f10d1fafceb9a98117ee101736'
  bluesnap:
    :user: "API_14177682984271105511385"
    :password: "Robin123"
    :store_id: "14253"
    :public_key: "10001$e1c3042d3facf7bd48f4fe4149c0711ff96c350c4ff41c7a0515c06e32322531c6d609d45f292bc006907086963d4cdef11849a4dd8eb6d629cbd2fed35f7ac44b25ae61a5c9b449bad56802e7bed9a7530c71855cd3c698a90b03a3c46de1074b0af2773e0223ea87c86b5a86e7eab6cf50bdc6063864a422e1d03acd6d1e03dcaab283c126fa576871e4c233c6383658a9cc048d4aabaa2519fc4088a7b62e9ee670b2fe340969d1fefb5b1aab7d8f3339f1c4e974baeffcf00c2f7d6da5327341e00fa89cd27890d01f9cabf7f082a7cda87b86694b684485100309a14f96ebefcd28b64761c26c51f83c5f1bbe31564dac6863f5888877d97e5cbde56de7"
    :base_url: "https://sandbox.bluesnap.com/services/2"
  yunpian:
    :api_key: "250b960f00ba9c461fc7559cb7740da2"
    :company_sign: "罗宾科技"
  qiniu:
    :access_key: "5bRVzHodaZbSwt6lLpO75opJo-TuSJyRoTlwkAON"
    :secret_key:  "RGzmCELncrd_AySF6hht0gElCtC0zxB2tWOjkIi7"
